version: '3.8'

services:
    currency_scraper:
        container_name: currency_scraper
        build: . # points Dockerfile
        env_file:
            - .env
        environment:
            - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo_db/
        ports:
            - 80:80
        volumes:
            - ./currency_scraper:/code/currency_scraper
        depends_on:
            - mongo_db

    mongo_db:
        container_name: mongo_db
        image: mongo
        restart: always
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - ./mongodb_data:/data/db
